import { Laundry, Service, Order } from '@/types';

export const dummyServices: Service[] = [
  {
    id: 's1',
    name: 'Cuci Reguler',
    description: 'Cuci dan setrika pakaian biasa',
    price: 8000,
    unit: 'kg',
    estimatedTime: 24,
    category: 'regular',
  },
  {
    id: 's2',
    name: 'Cuci Express',
    description: 'Cuci cepat 6 jam',
    price: 12000,
    unit: 'kg',
    estimatedTime: 6,
    category: 'express',
  },
  {
    id: 's3',
    name: 'Dry Clean',
    description: 'Dry clean untuk pakaian khusus',
    price: 25000,
    unit: 'pcs',
    estimatedTime: 48,
    category: 'dry-clean',
  },
  {
    id: 's4',
    name: 'Setrika Saja',
    description: 'Hanya setrika tanpa cuci',
    price: 5000,
    unit: 'kg',
    estimatedTime: 12,
    category: 'ironing',
  },
  {
    id: 's5',
    name: 'Cuci Karpet',
    description: 'Cuci karpet ukuran kecil',
    price: 50000,
    unit: 'pcs',
    estimatedTime: 72,
    category: 'regular',
  },
];

export const dummyLaundries: Laundry[] = [
  {
    id: 'l1',
    name: 'Laundry Express Jakarta',
    description: 'Laundry cepat dan berkualitas dengan layanan pick-up & delivery gratis',
    address: 'Jl. Sudirman No. 123, Jakarta Pusat',
    rating: 4.8,
    reviewCount: 234,
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800',
    priceRange: 'Rp 8.000 - Rp 25.000',
    distance: 2.5,
    isOpen: true,
    operatingHours: {
      open: '08:00',
      close: '20:00',
    },
    services: [dummyServices[0], dummyServices[1], dummyServices[2], dummyServices[3]],
  },
  {
    id: 'l2',
    name: 'Clean & Fresh Laundry',
    description: 'Spesialis dry clean dan cuci premium dengan teknologi terbaru',
    address: 'Jl. Thamrin No. 45, Jakarta Pusat',
    rating: 4.9,
    reviewCount: 189,
    image: 'https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?w=800',
    priceRange: 'Rp 10.000 - Rp 50.000',
    distance: 3.2,
    isOpen: true,
    operatingHours: {
      open: '07:00',
      close: '21:00',
    },
    services: [dummyServices[0], dummyServices[2], dummyServices[3], dummyServices[4]],
  },
  {
    id: 'l3',
    name: 'Quick Wash Laundry',
    description: 'Layanan express 6 jam dengan harga terjangkau',
    address: 'Jl. Gatot Subroto No. 78, Jakarta Selatan',
    rating: 4.6,
    reviewCount: 156,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    priceRange: 'Rp 7.000 - Rp 20.000',
    distance: 5.1,
    isOpen: true,
    operatingHours: {
      open: '08:00',
      close: '22:00',
    },
    services: [dummyServices[0], dummyServices[1], dummyServices[3]],
  },
  {
    id: 'l4',
    name: 'Premium Laundry Service',
    description: 'Layanan premium dengan perawatan khusus untuk pakaian mahal',
    address: 'Jl. Kemang Raya No. 12, Jakarta Selatan',
    rating: 4.7,
    reviewCount: 98,
    image: 'https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=800',
    priceRange: 'Rp 15.000 - Rp 75.000',
    distance: 7.8,
    isOpen: false,
    operatingHours: {
      open: '09:00',
      close: '18:00',
    },
    services: [dummyServices[2], dummyServices[4]],
  },
  {
    id: 'l5',
    name: 'Eco Laundry',
    description: 'Laundry ramah lingkungan dengan detergen organik',
    address: 'Jl. Kebayoran Baru No. 56, Jakarta Selatan',
    rating: 4.5,
    reviewCount: 201,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    priceRange: 'Rp 8.500 - Rp 30.000',
    distance: 4.3,
    isOpen: true,
    operatingHours: {
      open: '07:30',
      close: '19:30',
    },
    services: [dummyServices[0], dummyServices[1], dummyServices[3]],
  },
  {
    id: 'l6',
    name: '24/7 Laundry',
    description: 'Buka 24 jam untuk kenyamanan Anda',
    address: 'Jl. Senopati No. 34, Jakarta Selatan',
    rating: 4.4,
    reviewCount: 312,
    image: 'https://images.unsplash.com/photo-1556912172-45b7abe8b7e8?w=800',
    priceRange: 'Rp 9.000 - Rp 22.000',
    distance: 6.2,
    isOpen: true,
    operatingHours: {
      open: '00:00',
      close: '23:59',
    },
    services: [dummyServices[0], dummyServices[1], dummyServices[3]],
  },
];

export const dummyOrders: Order[] = [
  {
    id: 'o1',
    laundryId: 'l1',
    laundryName: 'Laundry Express Jakarta',
    services: [
      {
        serviceId: 's1',
        serviceName: 'Cuci Reguler',
        quantity: 3,
        price: 8000,
        unit: 'kg',
      },
      {
        serviceId: 's3',
        serviceName: 'Setrika Saja',
        quantity: 2,
        price: 5000,
        unit: 'kg',
      },
    ],
    totalPrice: 34000,
    status: 'washing',
    createdAt: '2024-01-15T10:30:00Z',
    estimatedPickup: '2024-01-15T14:00:00Z',
    estimatedDelivery: '2024-01-16T18:00:00Z',
    address: 'Jl. Contoh No. 123, Jakarta',
    notes: 'Mohon hati-hati dengan pakaian putih',
  },
  {
    id: 'o2',
    laundryId: 'l2',
    laundryName: 'Clean & Fresh Laundry',
    services: [
      {
        serviceId: 's2',
        serviceName: 'Cuci Express',
        quantity: 2,
        price: 12000,
        unit: 'kg',
      },
    ],
    totalPrice: 24000,
    status: 'ready',
    createdAt: '2024-01-14T08:00:00Z',
    estimatedPickup: '2024-01-14T09:00:00Z',
    estimatedDelivery: '2024-01-14T15:00:00Z',
    address: 'Jl. Contoh No. 123, Jakarta',
  },
  {
    id: 'o3',
    laundryId: 'l3',
    laundryName: 'Quick Wash Laundry',
    services: [
      {
        serviceId: 's3',
        serviceName: 'Dry Clean',
        quantity: 1,
        price: 25000,
        unit: 'pcs',
      },
    ],
    totalPrice: 25000,
    status: 'delivered',
    createdAt: '2024-01-13T12:00:00Z',
    estimatedPickup: '2024-01-13T13:00:00Z',
    estimatedDelivery: '2024-01-15T16:00:00Z',
    address: 'Jl. Contoh No. 123, Jakarta',
  },
];

